<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Expires" content="0">
    <title>Atur Jadwal Pencucian - Prismo</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="{{ asset('css/booking.css') }}?v={{ time() }}">
    <script>
        // Inject business data from backend
        window.mitraBusinessData = @json($businessData ?? null);
    </script>
    <script src="{{ asset('js/booking.js') }}?v={{ time() }}" defer></script>
</head>
<body>
    <div class="container">
        <!-- Left Section -->
        <div class="left-section">
            <div class="header">
                <div class="logo">
                    <img src="{{ asset('images/logo.png') }}" alt="Prismo Logo">
                </div>
                <button class="back-btn" onclick="window.location.href='{{ url('/customer/detail-mitra/minipro/' . $businessData['mitraId']) }}'">
                    <i class="fas fa-arrow-left"></i> Kembali
                </button>
            </div>

            <h1>Atur Jadwal Pencucian Anda</h1>

            <!-- Business Hours Info -->
            <div class="business-hours">
                <div class="hours-info" id="breakTimesInfo">
                    <i class="fas fa-utensils"></i>
                    <span>Istirahat: <strong id="breakTimes">Pilih tanggal untuk melihat waktu istirahat</strong></span>
                </div>
            </div>

            <!-- Calendar Section -->
            <div class="calendar">
                <div class="section-title">Pilih Tanggal</div>
                <div class="calendar-grid">
                    <!-- Headers -->
                    <div class="calendar-header">Sen</div>
                    <div class="calendar-header">Sel</div>
                    <div class="calendar-header">Rab</div>
                    <div class="calendar-header">Kam</div>
                    <div class="calendar-header">Jum</div>
                    <div class="calendar-header">Sab</div>
                    <div class="calendar-header">Min</div>
                    <!-- Calendar days will be generated by JavaScript -->
                </div>
            </div>

            <!-- Time Section -->
            <div class="form-section">
                <div class="section-title">Pilih Jam</div>
                <div class="time-selection">
                    <div class="time-grid" id="timeGrid">
                        <!-- Time slots will be generated by JavaScript -->
                    </div>
                </div>
            </div>

            <!-- Vehicle Info Section -->
            <div class="form-section">
                <div class="section-title">Kendaraan</div>
                <div class="form-row">
                    <div class="form-group">
                        <label class="required">Merek</label>
                        <input type="text" id="merek" placeholder="Mercedes" oninput="updateSummary()">
                    </div>
                    <div class="form-group">
                        <label class="required">Tipe</label>
                        <input type="text" id="tipe" placeholder="A-Class" oninput="updateSummary()">
                    </div>
                    <div class="form-group">
                        <label class="required">Nomer Polisi</label>
                        <input type="text" id="nopol" placeholder="B 2346 NT" oninput="updateSummary()">
                    </div>
                </div>
            </div>

            <!-- Additional Info Section -->
            <div class="form-section">
                <div class="section-title">Informasi Lainnya</div>
                <div class="form-row">
                    <div class="form-group full-width">
                        <label>Catatan Tambahan</label>
                        <input type="text" id="catatan" placeholder="Contoh: Cuci bagian dalam saja" oninput="updateSummary()">
                    </div>
                </div>

                <!-- Voucher Section -->
                <div class="voucher-section">
                    <div class="form-group voucher-input-group">
                        <label>Kode Voucher</label>
                        <div class="voucher-input-wrapper">
                            <input type="text" id="voucherCode" placeholder="Masukkan kode voucher" style="flex: 1;">
                            <button class="apply-voucher-btn" onclick="applyVoucher()" id="applyVoucherBtn">Gunakan</button>
                        </div>
                        <div class="voucher-message" id="voucherMessage" style="display: none;"></div>
                    </div>
                </div>

                <div class="toggle-section">
                    <div class="info-icon" onclick="showPointInfo()" title="Klik untuk info lebih lanjut">?</div>
                    <div class="toggle-content">
                        <div class="toggle-text">Tukarkan Point Prismo</div>
                        <div class="customer-points">Point Anda: <span id="customerPoints">{{ $businessData['customerPoints'] ?? 0 }}</span></div>
                    </div>
                    <label class="toggle-switch">
                        <input type="checkbox" id="usePoints" onchange="updateSummary()">
                        <span class="slider"></span>
                    </label>
                </div>
            </div>
        </div>

        <!-- Right Section - Summary -->
        <div class="right-section">
            <div class="summary-card">
                <div class="summary-title">Ringkasan Booking</div>
                
                <div class="summary-item">
                    <span class="label">Tanggal:</span>
                    <span class="value" id="summaryDate">-</span>
                </div>
                
                <div class="summary-item">
                    <span class="label">Jam:</span>
                    <span class="value" id="summaryTime">-</span>
                </div>
                
                <div class="summary-item">
                    <span class="label">Layanan:</span>
                    <span class="value" id="summaryService">Premium</span>
                </div>
                
                <div class="summary-item">
                    <span class="label">Merek:</span>
                    <span class="value" id="summaryMerek">-</span>
                </div>
                
                <div class="summary-item">
                    <span class="label">Tipe:</span>
                    <span class="value" id="summaryTipe">-</span>
                </div>
                
                <div class="summary-item">
                    <span class="label">Nomor Polisi:</span>
                    <span class="value" id="summaryNopol">-</span>
                </div>
                
                <div class="summary-item">
                    <span class="label">Catatan:</span>
                    <span class="value" id="summaryCatatan">-</span>
                </div>
                
                <div class="summary-item">
                    <span class="label">Estimasi Waktu:</span>
                    <span class="value">1 Jam</span>
                </div>
                
                <div class="summary-item">
                    <span class="label">Biaya Admin:</span>
                    <span class="value">Rp 1.000</span>
                </div>
                
                <div class="summary-item" id="voucherSection" style="display: none;">
                    <span class="label">Voucher:</span>
                    <span class="value voucher-discount" id="voucherDiscount">-Rp 0</span>
                </div>

                <div class="summary-item" id="pointSection" style="display: none;">
                    <span class="label">Point Telah Digunakan:</span>
                    <span class="value point-discount" id="pointDiscount">-Rp 0</span>
                </div>

                <div class="summary-total">
                    <span class="label">Total:</span>
                    <span class="value" id="summaryTotal">Rp 0</span>
                </div>

                <!-- Warning & Confirm Section -->
                <div style="max-width: 400px; width: 100%; margin: 20px auto 0;">
                    <label style="display: flex; align-items: flex-start; gap: 12px; padding: 16px; background: #E8F4FD; border-radius: 8px; cursor: pointer; margin-bottom: 16px;">
                        <input type="checkbox" id="agreeCheckbox" onchange="toggleConfirmButton()" style="margin-top: 2px; width: 18px; height: 18px; cursor: pointer; flex-shrink: 0;">
                        <span style="font-size: 14px; line-height: 1.5; color: #333;">Jangan tinggalkan barang-barang berharga anda di dalam mobil</span>
                    </label>
                    
                    <button class="confirm-btn" id="confirmBtn" onclick="confirmBooking()" disabled>Konfirmasi Booking</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Payment Modal -->
    <div class="modal-overlay" id="modalOverlay">
        <div class="modal">
            <div class="modal-header">
                <button class="back-btn" onclick="closeModal()">←</button>
                <h2 class="modal-title">Pembayaran</h2>
            </div>
            
            <div class="modal-content" id="paymentContent">
                <div class="payment-box">
                    <div class="qris-logo">QRIS</div>
                    <img src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 200 200'%3E%3Crect fill='white' width='200' height='200'/%3E%3Cpath fill='black' d='M10,10h30v30h-30z M50,10h10v10h-10z M70,10h10v10h-10z M90,10h10v10h-10z M110,10h10v10h-10z M130,10h10v10h-10z M160,10h30v30h-30z M10,50h10v10h-10z M30,50h10v10h-10z M50,50h10v10h-10z M70,50h10v10h-10z M90,50h10v10h-10z M110,50h10v10h-10z M130,50h10v10h-10z M160,50h10v10h-10z M180,50h10v10h-10z M10,70h10v10h-10z M30,70h10v10h-10z M70,70h30v30h-30z M130,70h10v10h-10z M160,70h10v10h-10z M180,70h10v10h-10z M10,90h10v10h-10z M30,90h10v10h-10z M130,90h10v10h-10z M160,90h10v10h-10z M180,90h10v10h-10z M10,110h10v10h-10z M30,110h10v10h-10z M50,110h10v10h-10z M110,110h10v10h-10z M130,110h10v10h-10z M160,110h10v10h-10z M180,110h10v10h-10z M50,130h10v10h-10z M70,130h10v10h-10z M90,130h30v30h-30z M130,130h10v10h-10z M10,160h30v30h-30z M50,160h10v10h-10z M70,160h10v10h-10z M130,160h10v10h-10z M160,160h30v30h-30z M50,180h10v10h-10z M70,180h10v10h-10z M130,180h10v10h-10z'/%3E%3C/svg%3E" class="qr-code" alt="QR Code">
                    <button class="download-btn" onclick="downloadQR()">Download Qris</button>
                </div>

                <div class="instructions">
                    <div class="instructions-title">Petunjuk Transfer Qris</div>
                    <ol>
                        <li>Download atau screenshot Qris</li>
                        <li>Buka aplikasi bank atau e-wallet yang mendukung Pembayaran Qris di Hp-mu.</li>
                        <li>Scan atau upload QR code diatas</li>
                        <li>Pastikan nama dan jumlah benar, lalu lanjutkan proses pembayaran</li>
                        <li>Setelah berhasil, kamu bisa cek status bayar untuk konfirmasi pembayaranmu.</li>
                    </ol>
                </div>

                <div class="upload-section">
                    <label class="upload-label">Upload Bukti Pembayaran</label>
                    <div class="info-notice" style="background: #e7f3ff; border-left: 4px solid #2196F3; padding: 12px 15px; margin-bottom: 15px; border-radius: 5px;">
                        <div style="display: flex; align-items: start; gap: 10px;">
                            <span style="font-size: 18px;">ℹ️</span>
                            <div style="flex: 1;">
                                <strong style="color: #003049; display: block; margin-bottom: 5px;">Pentingnya Bukti Pembayaran</strong>
                                <p style="margin: 0; color: #555; font-size: 14px; line-height: 1.5;">
                                    Bukti pembayaran Anda sangat penting untuk <strong>konfirmasi transaksi</strong> dan memudahkan proses <strong>refund</strong> jika terjadi pembatalan booking. Pastikan foto bukti pembayaran jelas dan dapat dibaca.
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="upload-area" id="uploadArea" onclick="document.getElementById('fileInput').click()">
                        <div class="upload-icon">📤</div>
                        <div class="upload-text">Klik untuk upload atau drag & drop</div>
                        <div class="upload-subtext">Format: JPG, PNG, JPEG (Max 5MB)</div>
                    </div>
                    <input type="file" id="fileInput" accept="image/jpeg,image/png,image/jpg" onchange="handleFileSelect(event)" style="display: none;">
                    
                    <div class="preview-container" id="previewContainer" style="display: none;">
                        <img id="previewImage" class="preview-image" alt="Preview">
                        <div class="file-info">
                            <span class="file-name" id="fileName"></span>
                            <button class="remove-btn" onclick="removeFile()">Hapus</button>
                        </div>
                    </div>

                    <button class="submit-btn" id="submitBtn" disabled onclick="submitPayment()">Konfirmasi Pembayaran</button>
                </div>
            </div>

            <div class="success-message" id="successMessage" style="display: none;">
                <div class="success-icon">✓</div>
                <div class="success-text">Pembayaran Berhasil Dikonfirmasi!</div>
                <div class="success-subtext">Terima kasih atas pembayaran Anda</div>
            </div>
        </div>
    </div>

    <!-- Invoice Modal -->
    <div class="modal-overlay" id="invoiceModal">
        <div class="invoice-container">
            <!-- Invoice Content -->
            <div class="invoice-content">
                <!-- Logo -->
                <div class="invoice-logo">
                    <!-- Ganti dengan logo Prismo jika ada -->
                    <div class="logo-text">prismo</div>
                </div>

                <div class="divider"></div>

                <!-- Partner Info -->
                <div class="partner-info">
                    <h3 class="partner-name" id="partnerName">Autospa Steam</h3>
                    <p class="partner-location" id="partnerLocation">Jakarta Pusat, DKI Jakarta</p>
                    <p class="partner-address" id="partnerAddress">Jl. Sudirman No. 45</p>
                    <p class="partner-phone" id="partnerPhone">0897654721</p>
                </div>

                <!-- Invoice Title -->
                <div class="invoice-title-section">
                    <div class="stars">* * * * * * * * * * * * * * * * * * * * * * * *</div>
                    <h2 class="invoice-title">Invoice</h2>
                    <div class="stars">* * * * * * * * * * * * * * * * * * * * * * * *</div>
                </div>

                <!-- Description Section -->
                <div class="description-section">
                    <h4 class="section-title">Deskripsi</h4>
                    
                    <div class="detail-row">
                        <span class="detail-label">Tanggal</span>
                        <span class="detail-value" id="invoiceDate">-</span>
                    </div>
                    
                    <div class="detail-row">
                        <span class="detail-label">Jam</span>
                        <span class="detail-value" id="invoiceTime">-</span>
                    </div>
                    
                    <div class="detail-row">
                        <span class="detail-label">Layanan</span>
                        <span class="detail-value" id="serviceName">Premium</span>
                    </div>
                    
                    <div class="detail-row">
                        <span class="detail-label">Merek</span>
                        <span class="detail-value" id="carBrand">-</span>
                    </div>
                    
                    <div class="detail-row">
                        <span class="detail-label">Tipe</span>
                        <span class="detail-value" id="carType">A - Class</span>
                    </div>
                    
                    <div class="detail-row">
                        <span class="detail-label">Nomer Polisi</span>
                        <span class="detail-value" id="licensePlate">B 2346 NT</span>
                    </div>
                    
                    <div class="detail-row" id="invoiceNotesRow" style="display: none;">
                        <span class="detail-label">Catatan</span>
                        <span class="detail-value" id="invoiceNotes">-</span>
                    </div>
                </div>

                <!-- Total Section -->
                <div class="total-section">
                    <div class="stars">* * * * * * * * * * * * * * * * * * * * * *</div>
                    <div class="total-row">
                        <span class="total-label">Total</span>
                        <span class="total-value" id="totalAmount">Rp 150.000</span>
                    </div>
                    <div class="stars">* * * * * * * * * * * * * * * * * * * * * *</div>
                </div>

                <!-- Thank You Message -->
                <p class="thank-you">Terimakasih telah menggunakan layanan kami.</p>
            </div>

            <!-- Action Buttons -->
            <div class="invoice-actions">
                <button class="btn btn-primary" onclick="downloadInvoice()">
                    <i class="fas fa-download"></i>
                    Download Invoice
                </button>
                <button class="btn btn-secondary" onclick="closeInvoice()">
                    <i class="fas fa-arrow-left"></i>
                    Selesai
                </button>
            </div>
        </div>
    </div>
</body>
</html>
